//
//  ScheduleModels.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ScheduleModels {
    enum Teachers {
        struct Request {
        }
        
        struct Response {
            let items: [TeacherItem]
        }
        
        struct ViewModel {
            let items: [TeacherItem]
        }
    }
    
    enum Classes {
        struct Request {
            let weekDay, weekNumber: Int
        }
        
        struct Response {
            let dayClasses: [[String: ClassItem]]
            let dayInfo: Request
        }
        
        struct ViewModel {
            let items: [Subject]
        }
    }
}
