//
//  NewsRouter.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsRoutingLogic {
    func displayNewsElement(viewModel: NewsModels.NewsElement.ViewModel)
}

final class NewsRouter: NSObject, NewsRoutingLogic {
    weak var viewController: NewsViewController?
    weak var newsElementVC: NewsElementVC?
    
    func displayNewsElement(viewModel: NewsModels.NewsElement.ViewModel) {
        print("⭕️ displaySpecificNews in NewsRouter")
        let vc = NewsElementVC()
        newsElementVC = vc
        newsElementVC?.configure(data: viewModel)
        
        guard let newsElementVC = newsElementVC,
              let viewController = viewController
        else {
            return
        }
        
        let delegate = viewController.presentDelegate
        newsElementVC.transitioningDelegate = delegate
        newsElementVC.modalPresentationStyle = .custom
        
        viewController.present(newsElementVC, animated: true)
    }
}
