//
//  NewsRouter.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsRoutingLogic {
    func displaySpecificNews(viewModel: NewsModels.SpecificNews.ViewModel)
}

protocol NewsDataPassing
{
  var dataStore: NewsDataStore? { get }
}

final class NewsRouter: NSObject, NewsRoutingLogic, NewsDataPassing {
  weak var viewController: NewsViewController?
  var specificNewsVC = SpecificNewsVC()
  var dataStore: NewsDataStore?
  
  // MARK: Routing
    func displaySpecificNews(viewModel: NewsModels.SpecificNews.ViewModel) {
        print("⭕️ displaySpecificNews in NewsRouter")
        self.passData(viewModel: viewModel)
        DispatchQueue.main.sync {
//            self.viewController?.navigationController?.pushViewController(self.specificNewsVC, animated: true)
            self.viewController?.navigationController?.present(self.specificNewsVC, animated: true)
            
        }
    }

  // MARK: Navigation

  
  // MARK: Passing data
    
    func passData(viewModel: NewsModels.SpecificNews.ViewModel) {
        print("⭕️ passData in NewsRouter")
        specificNewsVC.data = viewModel
    }
}
