//
//  NewsPresenter.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsPresentationLogic {
    func presentNews(response: NewsModels.News.Response)
}

final class NewsPresenter: NewsPresentationLogic {
    
  weak var viewController: NewsDisplayLogic?
  
  // MARK: Do something
  
  func presentNews(response: NewsModels.News.Response) {
      print("⭕️ presentNews in NewsPresenter")

      
      var news = [NewsCollectionItem]()
    
      for item in response {
          let element = NewsCollectionItem(content: .news(config: .init(
            id: item.id,
            name: item.name,
            image: item.image)))
          news.append(element)
      }
      
      let viewModel = NewsModels.News.ViewModel(news)
      viewController?.displayNews(viewModel: viewModel)
  }
}
