//
//  NewsRouter.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsRoutingLogic {
    func displayNewsElement(viewModel: NewsModels.NewsElement.ViewModel)
}

protocol NewsDataPassing {
  var dataStore: NewsDataStore? { get }
}

final class NewsRouter: NSObject, NewsRoutingLogic, NewsDataPassing {
  weak var viewController: NewsViewController?
  var dataStore: NewsDataStore?
  
    func displayNewsElement(viewModel: NewsModels.NewsElement.ViewModel) {
        print("⭕️ displaySpecificNews in NewsRouter")
        let vc = NewsElementVC(data: viewModel)
        viewController?.hideTabBar()
        UIView.transition(from: self.viewController!.view, to: vc.view, duration: 0.35, options: .transitionCrossDissolve)
        self.viewController?.navigationController?.pushViewController(vc, animated: false)
    }
}
