//
//  ScheduleRouter.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScheduleRoutingLogic {
    func presentPersonSettings(teachersList: ScheduleModels.Teachers.ViewModel)
}

final class ScheduleRouter: NSObject, ScheduleRoutingLogic {
    weak var viewController: ScheduleViewController?
  
    func presentPersonSettings(teachersList: ScheduleModels.Teachers.ViewModel) {
        let vc = TeacherListVC(teachers: teachersList)
        if let presentationController = vc.presentationController as? UISheetPresentationController {
            presentationController.detents = [.medium()]
        }
        viewController?.navigationController?.present(vc, animated: true)
    }
}
