//
//  ScheduleInteractor.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScheduleBusinessLogic
{
  func getTeacherslist(request: Schedule.Something.Request)
}

final class ScheduleInteractor: ScheduleBusinessLogic {
  var presenter: SchedulePresentationLogic?
    
    
  // MARK: Do something
  
  func getTeacherslist(request: Schedule.Something.Request) {
   
    
    let response = Schedule.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
