//
//  ScheduleModels.swift
//  MIREA Application
//
//  Created by Кирилл Пигалкин on 04.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ScheduleModels {
    enum Teachers {
        struct Request {
            //
        }
      
        typealias Response = [ResponseElement]
        struct ResponseElement: Codable {
            let id: Int
            let name: String
        }
          
        typealias ViewModel = [ResponseElement]
    }
    
    enum Classes {
        struct Request {
            let weekDay, weekNumber: Int
        }
        
        struct ResponseValue: Codable {
            let even, odd: [Subject]
        }
        struct Subject: Codable {
            let name, room, type, group, strWeeks: String
            let number, wdNum: Int
            let weeks: [Int]

            private enum CodingKeys: String, CodingKey {
                case name, number
                case wdNum = "wd_num"
                case group, type, room, weeks, strWeeks
            }
        }
        typealias ResponseItems = [[String: ResponseValue]]
        
        struct Response {
            let dayClasses: ResponseItems
            let dayInfo: Request
        }
        
        typealias ViewModel = [Subject]
    }
}
